FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch-run

# Defines our working directory in container
WORKDIR /usr/src/app

RUN install_packages wget nginx nginx-light

COPY static /var/www/html/static
COPY nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]
